from django.db import models


class Guaranteed(models.Model):
    food = models.OneToOneField('food.Food', on_delete=models.CASCADE, related_name='guaranteed', primary_key=True)
    protein = models.FloatField(default=0)
    fat = models.FloatField(default=0)
    fibre = models.FloatField(default=0)
    ash = models.FloatField(default=0)
    carbs = models.FloatField()
    moisture = models.FloatField(default=0)
    calcium = models.FloatField(default=0)
    phosphorus = models.FloatField(default=0)
    potassium = models.FloatField(default=0)
    sodium = models.FloatField(default=0)
    chloride = models.FloatField(default=0)
    magnesium = models.FloatField(default=0)
    iron = models.FloatField(default=0)
    copper = models.FloatField(default=0)
    manganese = models.FloatField(default=0)
    zinc = models.FloatField(default=0)
    iodine = models.FloatField(default=0)
    selenium = models.FloatField(default=0)
    vitamin_a = models.FloatField(default=0)
    vitamin_d = models.FloatField(default=0)
    vitamin_e = models.FloatField(default=0)
    vitamin_k = models.FloatField(default=0)
    thiamine = models.FloatField(default=0)
    riboflavin = models.FloatField(default=0)
    pantothenic_acid = models.FloatField(default=0)
    niacin = models.FloatField(default=0)
    pyridoxine = models.FloatField(default=0)
    folic_acid = models.FloatField(default=0)
    biotin = models.FloatField(default=0)
    vitamin_B12 = models.FloatField(default=0)
    choline = models.FloatField(default=0)
    taurine = models.FloatField(default=0)
    omega3 = models.FloatField(default=0)
    omega6 = models.FloatField(default=0)
    dha = models.FloatField(default=0)
    epa = models.FloatField(default=0)

