# Generated by Django 3.0.7 on 2020-06-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('manufacturer_url', models.CharField(max_length=1024)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('active', models.PositiveSmallIntegerField(default=1)),
                ('ingredient_score', models.PositiveSmallIntegerField()),
                ('nutrition_score', models.PositiveSmallIntegerField()),
                ('image', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='FoodFor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('active', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FoodStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('active', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('active', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientParent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('active', models.PositiveSmallIntegerField(default=1)),
                ('allergen', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('active', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('quality', models.PositiveSmallIntegerField()),
                ('active', models.PositiveSmallIntegerField(default=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('allergen', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.IngredientParent')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.IngredientType')),
            ],
        ),
        migrations.CreateModel(
            name='Guaranteed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('fiber', models.FloatField()),
                ('ash', models.FloatField()),
                ('moisture', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_percent', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='food_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodFor'),
        ),
        migrations.AddField(
            model_name='food',
            name='food_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodStage'),
        ),
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodType'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(related_name='foods', through='food.FoodIngredient', to='food.Ingredient'),
        ),
        migrations.CreateModel(
            name='DryMatter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('fiber', models.FloatField()),
                ('ash', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('total', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
            ],
        ),
    ]
