# Generated by Django 3.0.7 on 2020-06-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_stage',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_for',
        ),
        migrations.AddField(
            model_name='food',
            name='health',
            field=models.ManyToManyField(related_name='foods', to='food.FoodFor'),
        ),
    ]
