# Generated by Django 3.0.7 on 2020-06-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200628_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='stage',
        ),
        migrations.AddField(
            model_name='food',
            name='stage',
            field=models.ManyToManyField(related_name='foods', to='food.FoodStage'),
        ),
    ]
