# Generated by Django 3.0.7 on 2020-06-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200629_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calorie',
            name='food',
        ),
        migrations.RemoveField(
            model_name='drymatter',
            name='food',
        ),
        migrations.RemoveField(
            model_name='guaranteed',
            name='food',
        ),
        migrations.AlterField(
            model_name='calorie',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='food.Food'),
        ),
        migrations.AlterField(
            model_name='drymatter',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='food.Food'),
        ),
        migrations.AlterField(
            model_name='guaranteed',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='food.Food'),
        ),
    ]
