# Generated by Django 3.0.7 on 2020-06-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200630_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorie',
            old_name='id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='drymatter',
            old_name='id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='guaranteed',
            old_name='id',
            new_name='food',
        ),
    ]
