# Generated by Django 3.0.7 on 2020-06-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20200630_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientQuality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('active', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
