# Generated by Django 3.0.7 on 2020-06-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_ingredientquality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.IngredientQuality'),
        ),
    ]
