# Generated by Django 3.0.7 on 2020-07-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200701_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodingredient',
            name='top_ingredient',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
